POST http://localhost:5000/api/v1/user/register
Content-Type: application/json

{
    "name" : "wello", 
    "email" : "wello@test.11223",
    "password" : "123"
}

###
POST http://localhost:5000/api/v1/user/login
Content-Type: application/json

{
 
    "email" : "walid.daou@gmail.com",
    "password" : "123"
}


###
POST http://localhost:5000/api/v1/store/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJ3ZWxsbyIsImVtYWlsIjoid2VsbG9AdGVzdC4xMTIyMyIsInBhc3N3b3JkIjoiIiwiX2lkIjoiNjViNTY5NzI1NDVlYzg2YTliOTNmZjI3IiwidXBkYXRlZEF0IjoiMjAyNC0wMS0yN1QyMDozNzowNi40NjBaIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0yN1QyMDozNzowNi40NjBaIiwiX192IjowfSwiaWF0IjoxNzA2Mzg3ODI2fQ.Ry0Az9NCBEb_VdiGMQWSyzPYgsbO8JOF4bjEuBBxSfQ
Content-Type: application/json


    {
        "name":"store1",
        "description":"the first store in the market ",
        "location": "lebanon",
        "owner": "65b4ed1d892abbe97d262cab"
    }

###

POST http://localhost:5000/api/v1/product/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJ3ZWxsbyIsImVtYWlsIjoid2VsbG9AdGVzdC4xMTIyMyIsInBhc3N3b3JkIjoiIiwiX2lkIjoiNjViNTY5NzI1NDVlYzg2YTliOTNmZjI3IiwidXBkYXRlZEF0IjoiMjAyNC0wMS0yN1QyMDozNzowNi40NjBaIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0yN1QyMDozNzowNi40NjBaIiwiX192IjowfSwiaWF0IjoxNzA2Mzg3ODI2fQ.Ry0Az9NCBEb_VdiGMQWSyzPYgsbO8JOF4bjEuBBxSfQ
Content-Type: application/json


     {  "name":"product 4",
            "price": 999,
        "description": " lidnoq zz best stuff ",
            "category": " dtt "
    }

//"_id": "65b4f86895ab6ffeb70a5941", id for product 1
###
PUT http://localhost:5000/api/v1/store/approve/65b56993545ec86a9b93ff2a
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YjdiNDIyYjUxMjIxM2RmZTExNTBkMyIsIm5hbWUiOiJiYWJ5IiwiZW1haWwiOiJiYWJ5QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0yOVQxNDoyMDoxOC40NzdaIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0yOVQxNDoyMDoxOC40NzdaIiwiX192IjowfSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwNjUzODA0Mn0
Content-Type: application/json

{
    "email":"wello@test.123",
     "approved": "true",
    "new": "true"
}


###
POST http://localhost:5000/api/v1/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YjUzNjFhMTI3MjU1YzY5NTFkOGU5YyIsIm5hbWUiOiJ3ZWxsbyIsImVtYWlsIjoid2VsbG9AdGVzdC4xMjIzIiwicGFzc3dvcmQiOiIiLCJ1cGRhdGVkQXQiOiIyMDI0LTAxLTI3VDE2OjU4OjAyLjY5MVoiLCJjcmVhdGVkQXQiOiIyMDI0LTAxLTI3VDE2OjU4OjAyLjY5MVoiLCJfX3YiOjB9LCJpYXQiOjE3MDYzNzg3MzN9.YaopKXsKcGfT-cLmFHFr3J_fWO5LRv4papHD9v7vv0U
Content-Type: application/json

###
GET http://localhost:5000/api/v1/store/find/65af9b3be2633b8e9cbc13a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YjUzNjFhMTI3MjU1YzY5NTFkOGU5YyIsIm5hbWUiOiJ3ZWxsbyIsImVtYWlsIjoid2VsbG9AdGVzdC4xMjIzIiwicGFzc3dvcmQiOiIiLCJ1cGRhdGVkQXQiOiIyMDI0LTAxLTI3VDE2OjU4OjAyLjY5MVoiLCJjcmVhdGVkQXQiOiIyMDI0LTAxLTI3VDE2OjU4OjAyLjY5MVoiLCJfX3YiOjB9LCJpYXQiOjE3MDYzNzg3MzN9.YaopKXsKcGfT-cLmFHFr3J_fWO5LRv4papHD9v7vv0U
Content-Type: application/json


###
GET http://localhost:5000/api/v1/store/list
Content-Type: application/json

